apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-service-2
  template:
    metadata:
      labels:
        app: micro-service-2
    spec:
      containers:
      - name: service-2-container
        image: micro2:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000